G-BLASTN 1.1 version released. Support NCBI-BLASTN 2.2.28 version.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -24,7 +24,7 @@ function stop_progress_ind {
   echo -en "\n"
 }
 
-ncbi_blast_version="ncbi-blast-2.2.26+-src"
+ncbi_blast_version="ncbi-blast-2.2.28+-src"
 working_dir=`pwd`
 nvcc=`which nvcc`
 if [[ ! -d ${working_dir}/log ]]; then
@@ -37,13 +37,14 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
-echo "Do you want to install GPU-BLAST on an existing installation of \"blastn\" [yes/no]"
+echo "Do you want to install GPU-BLASTN on an existing installation of \"blastn\" [yes/no]"
 echo "yes: you will be asked for the installation directory of the \"blastn\" executable"
 echo "no: will download and install \"${ncbi_blast_version}\""
 read user_input
 
 if [ $user_input == "yes" ]; then
-    echo "Please input the installation directory of \"blastn\" of \"${ncbi_blast_version}\""
+    echo "Please input the bin directory of \"blastn\" of \"${ncbi_blast_version}\""
+	echo "e.g.: /ssd/blast/src/ncbi-blast-2.2.28+-src/c++/GCC447-ReleaseMT64/bin"
     read installed_dir
     #check if the executable "blastn" exists in the given directory
     if [ ! -x $installed_dir/blastn ]; then
@@ -52,7 +53,7 @@ if [ $user_input == "yes" ]; then
 	exit 0
     else
 	blastn_version=`$installed_dir/blastn -version | grep blastn | awk '{print $NF}'`
-	if [ $blastn_version == "2.2.26+" ]; then 
+	if [ $blastn_version == "2.2.28+" ]; then 
 	    echo "\"blastn\" version $blastn_version is compatible"
 	else
 	    echo "\"blastn\" version $blastn_version is not supported"
@@ -63,11 +64,11 @@ if [ $user_input == "yes" ]; then
     #check if the source file "blast_engine.c" as a first check that the source code exists
     if [ ! -f "$installed_dir/../../src/algo/blast/core/blast_engine.c" ]; then
 	echo "Source code not detected."
-	echo "You must have the source code of \"$ncbi_blast_version\" to add GPU-BLAST"
+	echo "You must have the source code of \"$ncbi_blast_version\" to add GPU-BLASTN"
 	echo "Exiting..."
 	exit 0
     else
-	echo "Continuing with the installation of GPU-BLAST..."	
+	echo "Continuing with the installation of GPU-BLASTN..."	
 	download=0
     fi
 elif [ $user_input == "no" ]; then
@@ -82,53 +83,54 @@ fi
 if [ $download == 1 ]; then
     
   
-#Download the version 2.2.26 of NCBI BLAST
+#Download the version 2.2.28 of NCBI BLAST
     echo "Downloading NBCI BLAST"
-    #wget ftp://ftp.ncbi.nih.gov/blast/executables/blast+/2.2.26/${ncbi_blast_version}.tar.gz
-    #if [ $? -ne 0 ]; then
-#	echo -e "\nError downloading ${ncbi_blast_version}. Verify that the file exists in the server. Exiting..."
-#	exit 1
-#    fi
+    wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.2.28/${ncbi_blast_version}.tar.gz
+    if [ $? -ne 0 ]; then
+	echo -e "\nError downloading ${ncbi_blast_version}. Verify that the file exists in the server. Exiting..."
+	exit 1
+    fi
     echo -e "\nExtracting NCBI BLAST"
-    #progress_ind &
-    #pid=$!
-    #trap "stop_progress_ind $pid; exit" INT TERM EXIT
+    progress_ind &
+    pid=$!
+    trap "stop_progress_ind $pid; exit" INT TERM EXIT
     
     tar -xzf ${ncbi_blast_version}.tar.gz
 
-    #stop_progress_ind $pid
+    stop_progress_ind $pid
 
     #Modify NCBI BLAST configuration files
-    #NCBI BLAST 2.2.26 installation script is not able to find touch on some Linux systems. 
+    #NCBI BLAST 2.2.28 installation script is not able to find touch on some Linux systems. 
     #NCBI BLAST has a fix here http://www.ncbi.nlm.nih.gov/viewvc/v1?view=rev&revision=53139
-    #but that was released after version 2.2.26, thus I replace the five files to fix this problem
-    echo -e "\nModifying NCBI BLAST configuration files"
-    cd ${working_dir}/gpu_blast/
-    sh ./modify_conf ${working_dir} > ${working_dir}/log/modify_conf.output
+    #but that was released after version 2.2.28, thus I replace the five files to fix this problem
+    #echo -e "\nModifying NCBI BLAST configuration files"
+    #cd ${working_dir}/gpu_blast/
+    #sh ./modify_conf ${working_dir} > ${working_dir}/log/modify_conf.output
+	
 
-    if [ $? -ne 0 ]; then
-        echo -e "\nError: while modirying the source code files. See \"modify_conf.output\" for more details. Exiting..."
-        exit 1
-    fi
+    #if [ $? -ne 0 ]; then
+    #    echo -e "\nError: while modirying the source code files. See \"modify_conf.output\" for more details. Exiting..."
+    #    exit 1
+    #fi
 
 #Move to the c++ directory which contains the configuration script
     cd ${working_dir}/${ncbi_blast_version}/c++/
     
 #Configure NCBI BLAST
-    #progress_ind &
-    #pid=$!
-    #trap "stop_progress_ind $pid; exit" INT TERM EXIT
-    configuration_options="./configure --without-debug --with-mt --without-sybase --without-fastcgi --without-fltk --without-sssdb --without-sss --without-geo --without-sp --without-orbacus --without-boost"
+    progress_ind &
+    pid=$!
+    trap "stop_progress_ind $pid; exit" INT TERM EXIT
+    configuration_options="./configure --without-debug --with-mt --without-sybase --without-fastcgi --without-sssdb --without-sss --without-geo --without-sp --without-orbacus --without-boost"
     echo -e "\nConfiguring ${ncbi_blast_version} with options:"
     echo -e "\n${configuration_options}"
     echo -e "\nIf you want to change these options edit the file \"install\", delete the directory ${ncbi_blast_version}, and return install"
-    $configuration_options >  ${working_dir}/log/configure.output
+    $configuration_options &>  ${working_dir}/log/configure.output
     if [ $? -ne 0 ]; then
 	echo -e "\nError in configuring NCBI BLAST installation. Look at \"configure.output\" for more information"
 	exit 1
     fi
     
-    #stop_progress_ind $pid
+    stop_progress_ind $pid
 
     #extract the installation directory    
     makefile_line=`cat ../../log/configure.output | grep Tools`
@@ -161,8 +163,10 @@ echo ${cxx_dir}
 
 #Modify NCBI BLAST files
 echo -e "\nModifying NCBI BLAST files"
-cd ${working_dir}/gpu_blast/
-sh ./modify ${cxx_dir} > ${working_dir}/log/modify.output
+cd ${working_dir}
+echo ${working_dir}
+#sh ./modify ${cxx_dir} > ${working_dir}/log/modify.output
+`cp -rf ./c++ ${ncbi_blast_version}`
 
 if [ $? -ne 0 ]; then
     echo -e "\nError: while modirying the source code files. See \"modify.output\" for more details. Exiting..."
